In [63]:
import numpy as np

dataset = np.array([[10, 15],
                    [15, 20], 
                    [13, 16], 
                    [16, 19], 
                    [5, 12], 
                    [21, 8]])
target = np.array([11, 19])
labels = np.array(['a1', 'a2', 'a3', 'a4', 'a5', 'a6'])
distance = (((dataset - target) ** 2).sum(axis=1)) ** .5
print(labels[distance.argmin()])

a3


In [61]:
a1 = np.array([[1,4,0], [5,0,7], [8,9,10]])
print(a1.transpose())
a1 = a1.flatten()
print(a1.argsort())

[[ 1  5  8]
 [ 4  0  9]
 [ 0  7 10]]
[2 4 0 1 3 5 6 7 8]


In [42]:
a1 = np.array([[1,4,0], [5,0,7], [8,9,10]])
print(a1[:1])
print(a1[1:])
print(a1[1,:])
print(a1[0,:])
print(a1[:,1])
print(a1[:,2])
print(a1.sum(axis=1))
print(a1.sum(axis=0))
print(a1.max(axis=0))
print(a1.min(axis=0))

[[1 4 0]]
[[ 5  0  7]
 [ 8  9 10]]
[5 0 7]
[1 4 0]
[4 0 9]
[ 0  7 10]
[ 5 12 27]
[14 13 17]
[ 8  9 10]
[1 0 0]
[[ 5  0  7]
 [ 8  9 10]]


In [38]:
help(np.sum)

Help on function sum in module numpy:

sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>)
    Sum of array elements over a given axis.
    
    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        integer.  In that case, if `a` 

In [31]:
a1 = np.array([[1,4,0], [5,0,7]])
print(a1.ndim)
print(a1.shape)
print(a1.size) # We use np function to get the size
print(len(a1)) # We use builtin function to get the size of array
print(list(a1)) # Builtin class list to convert into list
print(a1.tolist()) # Numpy system call to get the list
print(a1.all())
print(a1.any())
print(a1.itemsize)
print(a1.sum())
print(a1.mean())
print(a1.std())
print(a1.var())
print(a1.max())
print(a1.min())
a1.sort()
print(a1)

2
(2, 3)
6
2
[array([1, 4, 0]), array([5, 0, 7])]
[[1, 4, 0], [5, 0, 7]]
False
True
8
17
2.8333333333333335
2.6718699236468995
7.138888888888888
7
0
[[0 1 4]
 [0 5 7]]


In [32]:
a1 = np.array([[1,4,0], [5,0,7]])
print(a1.argmax())
print(a1.argmin())
print(a1.argsort())

5
2
[[2 0 1]
 [1 0 2]]


In [23]:
a1 = np.array([2,5, 3, 10, 0], dtype=float)

print(a1.argmax())
print(a1.argmin())
print(a1.argsort())

3
4
[4 0 2 1 3]


In [28]:
print(a1 + 2) # arithmatic 
print(a1 ** 2) # arithmatic 
print(a1 / 2) # arithmatic 
print(a1 - 2) # arithmatic 
print(a1[a1 % 2 == 0]) # masking
mask = a1 % 2 == 0
print(a1[mask])

[ 4.  7.  5. 12.  2.]
[  4.  25.   9. 100.   0.]
[1.  2.5 1.5 5.  0. ]
[ 0.  3.  1.  8. -2.]
[ 2. 10.  0.]
[ 2. 10.  0.]


In [21]:
# Array and Matrices -
# single datatype
a1 = np.array([1,2,3], dtype=float)
print(a1.ndim)
print(a1.shape)
print(a1.size) # We use np function to get the size
print(len(a1)) # We use builtin function to get the size of array
print(list(a1)) # Builtin class list to convert into list
print(a1.tolist()) # Numpy system call to get the list
print(a1.all())
print(a1.any())
print(a1.itemsize)
print(a1.sum())
print(a1.mean())
print(a1.std())
print(a1.var())
print(a1.max())
print(a1.min())
a1.sort()
print(a1)
#dir(a1)

1
(3,)
3
3
[1.0, 2.0, 3.0]
[1.0, 2.0, 3.0]
True
True
8
6.0
2.0
0.816496580927726
0.6666666666666666
3.0
1.0
[1. 2. 3.]


In [4]:
import timeit
import numpy as np # Extensive {Python Library - for processing numberical data}

py_sec = timeit.timeit('sum(range(1, 10000))', number=10000)
np_sec = timeit.timeit('np.sum(np.arange(1, 10000))', 
                       setup='import numpy as np', number=10000)

print(py_sec)
print(np_sec)


2.4528635169999973
0.18315250399999172
